# Generated by Django 4.2.7 on 2023-12-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eid", models.IntegerField()),
                ("ename", models.CharField(max_length=32)),
                ("esal", models.IntegerField()),
                ("eloc", models.CharField(max_length=32)),
            ],
        ),
    ]
